Testing throw of caught exception and rethrow 